config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'
  resources :stories do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable

  validates :body, presence: true

  def root_story
    story = self
    story = story.commentable until story.commentable.is_a?(Story)
    story.commentable
  end
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true, length: { maximum: 110 }
  validates :url, presence: true

  def url_host
    URI("#{self.url}").host || "unknown"
  end

  def all_comments
    parent_comments + child_comments
  end

    private
    
    def parent_comments
      Comment.where(commentable_id: id)
    end

    def child_comments
      Comment.where(commentable_id: parent_comments.map(&:id))
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
    @story_parent = @comment.root_story
  end

  def create
    @comment = @commentable.comments.new comment_params

    if @comment.save
      redirect_to story_path(@comment.root_story), notice: 'Your comment was successfully posted!'
    else
      redirect_back fallback_location: root_path, notice: "Your comment wasn't posted!"
    end
  end

    private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Story.find_by_id(params[:story_id]) if params[:story_id]
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_produto, only: [:show, :destroy]

  def index
    @stories = Story.all
  end

  def show
  end

  def new
    @story = Story.new
    render :new
  end

  def create
    @story = Story.new story_params

    if @story.save
      flash[:notice] = "Story submitted successfully!"
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    if @story.destroy
      flash[:notice] = "Story deleted successfully!"
      redirect_to root_url
    else
      flash.now[:notice] = "Fail to delete story."
      render :new
    end
  end

    private

    def story_params
      params.require(:story).permit(:title, :url)
    end

    def set_produto
      id = params[:id]
      @story = Story.find(id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/comments/_comment.html.erb
<% @story.errors.full_messages.each do |message| %>
  <div class="alert alert-danger">
    <%= message %>
  </div>
<% end %>

<li>
  <%= comment.body %>

  <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>

  <p>
    <small><%= link_to 'reply', comment %></small>
  </p>
  
  <ul>
    <div class="container">
      <%= render partial: 'comments/comment', collection: comment.comments %>
    </div>
  </ul>
</li>

app/views/comments/show.html.erb
<div class="container">
  <small>
    Submitted <%= time_ago_in_words(@comment.created_at) %> ago

    |

    parent on:
    <%= link_to "#{@story_parent.title} (#{@story_parent.url})", @story_parent.url %>
  </small>

  <p><%= @comment.body %></p>

  <%= form_for [@comment, Comment.new] do |f| %>
    <div class="form-group">
      <%= f.text_area :body, placeholder: 'Add a comment', class: 'form-control' %>
    </div>

    <%= f.submit 'Add comment', class: 'btn btn-primary form-control' %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Mini Hacker News', root_path, id: 'logo' %></li>
        <li><%= link_to 'home', root_url %></li>
        <li><%= link_to 'submit', new_story_url %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mini HackerNews</title>
    <%= render "layouts/rails_default" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stories/_form.html.erb
<% @story.errors.full_messages.each do |message| %>
  <div class="alert alert-danger">
    <%= message %>
  </div>
<% end %>

<%= form_for @story do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-primary form-control' %>
<% end %>

app/views/stories/_story.html.erb
<h2>
  <li>
    <p><%= link_to "#{story.title} (#{story.url_host})", story.url %></p>

    <small>
      <%= link_to "delete",
        story,
        method: :delete,
        data: { confirm: "Are you want to delete the story?" }
      %>

      |

      <% if story.all_comments.present? %>
        <%= link_to "#{story.all_comments.count} comments", story %>
      <% else %>
        <%= link_to "discuss", story %>
      <% end %>
    </small>
  </li>
</h2>

app/views/stories/index.html.erb
<div class="alert">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
</div>

<div class="container">
  <%= render @stories %>
</div>

app/views/stories/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/stories/show.html.erb
<div class="alert">
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
</div>

<div class="container">
  <p>
    <%= link_to @story.title, @story.url, target: '_blank' %>
    <small>Submitted <%= time_ago_in_words(@story.created_at) %> ago</small>
  </p>

  <%= form_for [@story, Comment.new] do |f| %>
    <div class="form-group">
      <%= f.text_area :body, placeholder: 'Add a comment', class: 'form-control' %>
    </div>

    <%= f.submit 'Add comment', class: 'btn btn-primary form-control' %>
  <% end %>

  <h3>Comments</h3>

  <ul>
    <%= render partial: 'comments/comment', collection: @story.comments %>
  </ul>
</div>